title: Finland-China Multi-cultural Education Association
slogan: "We believe education is about:"
author: 
email: some@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: 
github_username:  

sass:
    style: compressed


# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Service
    url: /service/
  - title: People
    url: /people/    
  - title: Contact
    url: /contact/

service:
  - imgurl: /assets/imgs/cn-lang.jpg
    title: Chinese language tutoring
    desc: Fusce consectetur est vel justo volutpat convallis. Nunc nec magna at enim fermentum faucibus efficitur sed mi. Nunc semper orci vitae porta faucibus. 
  - imgurl: /assets/imgs/hiker.png
    title: Educational tour
    desc: Donec malesuada sollicitudin pellentesque. Aliquam hendrerit rhoncus lectus at dignissim. 

boards:
  - imgurl: /assets/imgs/qing.jpg
    name: Qing Liu
    desc: MSc in Social Science with minor in Education Technology (University of Helsinki)
  - imgurl: /assets/imgs/jiahui.jpg
    name: Jiahui Yang
    desc: MSc in Microbiology (University of Helsinki)
  - imgurl: /assets/imgs/han.jpg
    name: Han Xiao
    desc: MSc in Computer Science (University of Helsinki)
  - imgurl: /assets/imgs/pekka.jpg
    name: Pekka
    desc: MSc in Political Science
    
include:
  - _pages	