email: some@gmail.com

twitter_username: 
github_username:  

baseurl: ""

sass:
    style: compressed


# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - name: service
    url: /service/
  - name: people
    url: /people/
  - name: contact
    url: /contact/

service:
  - cambridge
  - finland
  - tutor
  - counselling

boards:
  - qing
  - jiahui
  - pekka
  - han
  
    
include:
  - _pages


# mult-lingual configuration

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "fi", "cn"]

langs:
  en: English
  cn: 简体中文
  fi: Suomeksi

# icon code
flag_icons:
  en: gb
  cn: cn
  fi: fi
  
exclude_from_localizations: ["js", "imgs", "css", "flags"]  