email: some@gmail.com

twitter_username: 
github_username:  

baseurl: ""

sass:
    style: compressed


# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - name: service
    url: /service/
  - name: people
    url: /people/    
  - name: contact
    url: /contact/

service:
  - tutor        
  - tour

boards:
  - imgurl: /assets/imgs/qing.jpg
    name: Qing Liu
    desc: MSc in Social Science with minor in Education Technology (University of Helsinki)
  - imgurl: /assets/imgs/jiahui.jpg
    name: Jiahui Yang
    desc: MSc in Microbiology (University of Helsinki)
  - imgurl: /assets/imgs/han.jpg
    name: Han Xiao
    desc: MSc in Computer Science (University of Helsinki)
  - imgurl: /assets/imgs/pekka.jpg
    name: Pekka Sairanen (Lin Liu)
    desc: M.A.International Relations in Contemporary East Asia (with Distinction, University of Birmingham), B.Sc. Economics and Political Science (With Honours, University of Birmingham)
    
include:
  - _pages


# mult-lingual configuration

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "fi", "cn"]

langs:
  en: English
  cn: 简体中文
  fi: Suomeksi

# icon code
flag_icons:
  en: gb
  cn: cn
  fi: fi
  
exclude_from_localizations: ["js", "imgs", "css"]  